  services:

    backend:
      build: ./backend

      env_file:
        - ./backend/.env.local
           
    nginx_reverse_proxy:
      build: 
        context: ./nginx
      ports:
        - "0.0.0.0:3000:80"  
    
  
