  services:

    backend:
      build: ./backend
      # ports:
      #   - "3000:3000"
      env_file:
        - ./backend/.env.local
           
    nginx_reverse_proxy:
      build: 
        context: ./nginx
      ports:
        - "0.0.0.0:80:80"  
    
  
