  services:

    backend:
      build: ./backend
      # ports:
      #   - "3000:3000"
      env_file:
        - ./backend/.env.local
           
    nginx_reverse_proxy:
      build: 
        context: ./nginx
      ports:
        - "5000:80"  
    
    ytdl:
      build: ./ytdl
      ports:
        - "3001:3001"
  
