FROM oven/bun

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install


COPY . /app/.
ARG UPSTASH_REDIS_CONNECTION_STRING
ENV UPSTASH_REDIS_CONNECTION_STRING=$UPSTASH_REDIS_CONNECTION_STRING
ENV PORT 3000
ENV NODE_ENV production
CMD ["bun", "start"]

EXPOSE 3000