name: Create ENV

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: MAKE ENV FILE .env.production
      run: echo UPSTASH_REDIS_CONNECTION_STRING=${{secrets.UPSTASH_REDIS_CONNECTION_STRING}} >> .env.production
    